### ISSUE TITLE
Add installation dependencies (edje_cc not found) in README

### ISSUE THREAD

**Issue by sreecodeslayer** [sylveon/terminology-themes#1]
First of all, awesome work on the themes. I have been wanting to change the theme on this for quite a while. 

Now coming to the issue, well it's just a suggestion.
While installing, my ubuntu kept complaining about not having `edje_cc`. 
So I found out that I had to install:
[libedje](https://launchpad.net/ubuntu/trusty/+package/libedje-bin) : 

```bash
$ apt install libedje-bin
```
before I could install the themes using 
```bash
$ make install
```

It would be cool if you could just add the installation dependencies in README. I guess there are no other dependencies. At least this was all I needed to install.

**Comment by sylveon** [comment]
Thanks 😊 

This is still WIP, I haven't really took time to write a complete README yet. I'll do that right now.

BTW, the libedje and terminology versions in the official Ubuntu repos are [quite outdated](https://phab.enlightenment.org/w/packaging_status/). [The enlightenment project recommends using a more up-to-date PPA](https://www.enlightenment.org/distros/ubuntu-start#Packages)

**Comment by sreecodeslayer** [comment]
Awesome. Thanks for the heads up and the link :tada:
