### ISSUE TITLE
nord theme collides with Terminology itself

### ISSUE THREAD

**Issue by cyrevolt** [sylveon/terminology-themes#5]
We have both Terminology and this themes package in multiple distros (e.g., Arch Linux and Gentoo). However, both now have the nord theme - so the files collide. It appears that they are even different a bit:
https://github.com/sylveon/terminology-themes/commit/35a053d28ef45c3961457fe84f69e526c6729c9f
vs
https://github.com/billiob/terminology/commit/2b79f06e8d4c58d3b87afd49457b01a1f465863a

Does it make sense to remove it from here @sylveon? I'd otherwise just remove it when packaging this themes collection.

See also https://bugs.gentoo.org/656098 and https://aur.archlinux.org/packages/terminology-themes-git

**Comment by sylveon** [comment]
Side note, there's this in @billiob's commit message.

    I relied on sylveon/terminology-themes to figure out
    how to map the colors in that file…

lol

**Comment by cyrevolt** [comment]
Thanks, that was really quick! :)
