### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by SolarAquarion** [sylveon/terminology-themes#6]
edje_cc: Critical. GROUP terminology/background - state 'visible:0' does not exist for part 'popmedia_fill'; set in program 'popmedia_img2'

**Comment by anfly0** [comment]
I'm having the same problem..

**Comment by rbtylee** [comment]
You need to use efl 1.21. Edje in efl 1.22 is much stricter and these themes have not been fixed to compile under it. If using efl 1.21  or fixing the themes yourself is undoable for you, you can find the edj files at [Bodhi linuxes github for this package](https://github.com/BodhiDev/terminology-theme-pack). For the record, the errors the stricter edje complains about are real issues, just efl is rather  tolerant of errors and they never affected functionality as far as I know.

If I had time I would fork this repo and fix the themes for efl 1.22. At some point we (Bodhi Linux) are going to need these themes fixed for efl 1.22. But sadly we have had alot of issues trying to update to efl 1.22 and one serious one still unsolved. So me doing non directly bodhi related tasks is going to have to wait.

**Comment by sylveon** [comment]
This is mostly based off the stock themes, so it's possible we can just check what they did.

**Comment by sylveon** [comment]
https://github.com/billiob/terminology/commit/5abb8b0eb316b048c80fd7d292d1598b3392bd23#diff-a4f45576ee799b646d529d7e0fc40134

I don't have a working Linux installation anymore, I'll create a Manjaro VM real fast and verify if that fix works.
